### ISSUE TITLE
But how to use it? 

### ISSUE THREAD

**Issue by travstrat** [pytesNET/more-levels#1]
Excuse me but i dont understand how to use your beautiful plugin.
Please explain :-)

**Comment by SamBrishes** [comment]
Hellow,

The plugin itself doesn't require any configuration. You just need to upload the main folder to the `bl-plugins` directory of the respective website and activate it through the Bludit administration.

Now you can just use any page as parent using the usual way. So type in the title of the respective (sub) page in the "Parent" input field under the "Advanced" settings.

![](https://i.imgur.com/vZ8eGC7.png)


Sincerely,
Sam.
