### ISSUE TITLE
Does not corporate with TinyMCE editor

### ISSUE THREAD

**Issue by JTWebTools** [pytesNET/more-levels#4]
It breaks the TinyMCE editor. The editor does not appear if the plugin is activated.
With activated plugin:
![with-plugin](https://user-images.githubusercontent.com/62479795/85662698-846a0600-b6b8-11ea-9429-3e7a0ca35b1c.png)

Without the plugin:
![without-plugin](https://user-images.githubusercontent.com/62479795/85662725-8cc24100-b6b8-11ea-9f2a-5cba7d7d56e9.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks for the bug report, the new master branch should fix this issue.

Sincerely,
Sam.
